### ISSUE TITLE
Clean start for this code

### ISSUE THREAD

**Issue by omrihaim** [iSn0we/Whatsapp-Web#1]
Hey. When trying to run this code for the first time after download it states that clean isnt a function, and it can't find document. 

Can you please share how did you want us to use the code?

Thanks

**Comment by iSn0we** [comment]
how are you trying to run this? You have to run this in the browser javascript console. To open the console try to press Ctrl+Shift+J (or Cmd+Shift+J on a Mac).

**Comment by omrihaim** [comment]
It seems that whatsapp web changed their IDs structure and this is why the code needs to be updated. The x__id field is now constructed of 3 different IDs.
